### ISSUE TITLE
8. ¿Se utilizan animaciones y propiedades de transición de CSS?

### ISSUE THREAD

**Issue by axelriera** [ReinaFresita/Mercado-Liebre#6]
Podes probar a algun boton hacerle un cambio de color al pasarle el mouse por encima con :hover

EJ:
```css
boton1:hover {
        color:#76a0d6;
        transition: color, 0.5s;
}

```
